apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-sa # Nome do ServiceAccount
  namespace: luis-bruckner-dev # Certifique-se de usar o namespace correto
  annotations:
    tekton.dev/service-account: "true" # Adiciona uma anotação para facilitar o rastreamento de sua origem
secrets:
  # - name: github-secret # Secret com credenciais do GitHub para acesso ao repositório
  - name: dockerhub-secret # Secret com credenciais do Docker Hub para autenticação
  - name: github-gitops-secret # Secret com credenciais do GitHub para acesso ao repositório gitops
imagePullSecrets:
  - name: dockerhub-secret # Secret com credenciais do Docker Hub para pull de imagens
  # - name: github-secret
  - name: github-gitops-secret
