apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-sa # Nome do ServiceAccount
  namespace: hello-pipeline # Certifique-se de usar o namespace correto
  annotations:
    tekton.dev/service-account: "true" # Adiciona uma anotação para facilitar o rastreamento de sua origem
secrets:
  - name: dockerhub-secret-2 # Secret com credenciais do Docker Hub para autenticação
  - name: github-token # Secret com credenciais do GitHub para acesso ao repositório gitops
imagePullSecrets:
  - name: dockerhub-secret-2 # Secret com credenciais do Docker Hub para pull de imagens
