apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-event-listener
  namespace: luis-bruckner-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      bindings:
        - ref: github-binding
      template:
        ref: hello-pipeline-template
