apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-pipeline-run-
  namespace: hello-pipeline # Certifique-se de usar o namespace correto
spec:
  serviceAccountName: hello-sa
  pipelineRef:
    name: hello-pipeline

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: gitops-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: dockerconfig
      secret:
        secretName: dockerhub-secret-2
        items:
          - key: .dockerconfigjson
            path: config.json
