apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-pipeline-run-
  namespace: hello-pipeline # Certifique-se de usar o namespace correto
spec:
  pipelineRef:
    name: hello-pipeline

  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: hello-pvc

    - name: gitops-shared-data
      persistentVolumeClaim:
        claimName: hello-gitops-pvc

    - name: dockerconfig
      secret:
        secretName: dockerhub-secret-2
        items:
          - key: .dockerconfigjson
            path: config.json
